spring:
  application:
    name: db-sharding
  datasource:
    shard1:
      url: jdbc:postgresql://localhost:5433/shard1db
      username: user
      password: pass
    shard2:
      url: jdbc:postgresql://localhost:5434/shard2db
      username: user
      password: pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.transaction: TRACE
    org.springframework.orm.jpa: DEBUG
    com.example.sharding: DEBUG